"""Adapter contracts – Core never imports exchange-specific fields/codes."""
from __future__ import annotations
from decimal import Decimal
from typing import Any, Protocol, runtime_checkable
from signal_bot.domain.enums import OrderSide
from signal_bot.domain.models import SymbolRules

@runtime_checkable
class ExchangeCapabilities(Protocol):
    exchange_id: str
    supports_user_stream: bool
    supports_reduce_only: bool
    supports_trailing_stop: bool
    supports_position_mode_hedge: bool
    max_leverage: int
    def supports_protection_replace(self) -> bool: ...

@runtime_checkable
class MarketDataAdapter(Protocol):
    async def get_symbol_rules(self, symbol: str) -> SymbolRules: ...
    async def get_mark_price(self, symbol: str) -> Decimal: ...
    async def get_ticker(self, symbol: str) -> dict[str, Any]: ...

@runtime_checkable
class AccountAdapter(Protocol):
    async def get_balance(self) -> dict[str, Decimal]: ...
    async def get_positions(self, symbol: str | None = None) -> list[dict[str, Any]]: ...
    async def set_leverage(self, symbol: str, leverage: int) -> None: ...

@runtime_checkable
class ExecutionAdapter(Protocol):
    async def place_order(self, *, symbol: str, side: OrderSide, order_type: str, quantity: Decimal,
                          price: Decimal | None = None, client_order_id: str, reduce_only: bool = False,
                          extra: dict[str, Any] | None = None) -> dict[str, Any]: ...
    async def cancel_order(self, *, symbol: str, order_id: str | None = None, client_order_id: str | None = None) -> dict[str, Any]: ...
    async def get_order(self, *, symbol: str, order_id: str | None = None, client_order_id: str | None = None) -> dict[str, Any] | None: ...

@runtime_checkable
class ProtectionAdapter(Protocol):
    async def place_stop(self, *, symbol: str, side: OrderSide, stop_price: Decimal, quantity: Decimal,
                         client_order_id: str, reduce_only: bool = True) -> dict[str, Any]: ...
    async def replace_stop(self, *, symbol: str, existing_order_id: str, new_stop_price: Decimal,
                           quantity: Decimal, client_order_id: str) -> dict[str, Any]: ...
    async def cancel_protection(self, *, symbol: str, order_id: str | None = None, client_order_id: str | None = None) -> None: ...

@runtime_checkable
class StreamingAdapter(Protocol):
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def subscribe_orders(self) -> None: ...

@runtime_checkable
class PnLAdapter(Protocol):
    async def get_realized_pnl(self, symbol: str | None = None) -> Decimal: ...
    async def get_unrealized_pnl(self, symbol: str | None = None) -> Decimal: ...
